Algoritmo "LAÇO REPITA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Beatriz Chagas
// Data atual  : 09/09/2024

var
   contador:inteiro

inicio

   escreval ("-----------------------------")
   escreval (" LAÇO REPITA")
   escreval ("-----------------------------")
   repita
      Escreval("Chagas")
      contador <- contador + 1
   ate contador >= 10
   
Fimalgoritmo