Algoritmo "Exemplo Para"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jailson Santos
// Descrição   :  Apresentação do funcionamento do laço de repetição para
// Autor(a)    : Beatriz Chagas
// Data atual  : 09/09/2024

var
   contador:inteiro

Inicio

   escreval ("------------------------------")
   escreval (" LAÇO PARA")
   escreval ("------------------------------")

   para contador de 1 ate 10 passo 1 faca
    escreval(contador)
    fimpara


Fimalgoritmo